# Site settings
title: Luis Flávio da Costa Terra
description: Luis Flávio da Costa Terra
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Luis Flávio Terra
user_description: 
user_title: 
email: costaluisflavio@gmail.com
github_username:  lflaviocosta
facebook page: https://www.facebook.com/luisflavio.costa

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
